# SonarQube configuration
sonar.projectKey=bookstore-fastapi-backend
sonar.projectName=bookstore-fastapi-backend
sonar.sources=src/bookstore
sonar.tests=tests
sonar.python.version=3.12

# Coverage
sonar.python.coverage.reportPaths=coverage.xml

# Generated code exclusion
sonar.exclusions=src/generated/**/*
sonar.cpd.exclusions=src/generated/**/*
sonar.coverage.exclusions=src/generated/**/*
